<Project>
  <Sdk Name="Microsoft.NET.Sdk" />
  <Sdk Name="ktsu.Sdk" />
  <PropertyGroup>
    <NoWarn>$(NoWarn);CA1512;CA1510</NoWarn>
    <!-- CA1512: CA1512: Use ArgumentOutOfRangeException throw helper -->
    <!-- CA1512: CA1510: Use ArgumentNullException throw helper -->
  </PropertyGroup>
</Project>
